// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829011049_CascadeDeleteSolicitudBeneficiario")]
    partial class CascadeDeleteSolicitudBeneficiario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Beneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstructuraPresupuestariaId")
                        .HasColumnType("int");

                    b.Property<int?>("FuenteFinanciamientoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraPresupuestariaId");

                    b.HasIndex("FuenteFinanciamientoId");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("Domain.Entities.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Domain.Entities.DocumentosRespaldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("DocumentosRespaldo");
                });

            modelBuilder.Entity("Domain.Entities.EstructuraPresupuestaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstructurasPresupuestarias");
                });

            modelBuilder.Entity("Domain.Entities.FuenteFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuentesFinanciamiento");
                });

            modelBuilder.Entity("Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("Domain.Entities.Beneficiario", b =>
                {
                    b.HasOne("Domain.Entities.EstructuraPresupuestaria", "EstructuraPresupuestaria")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("EstructuraPresupuestariaId");

                    b.HasOne("Domain.Entities.FuenteFinanciamiento", "FuenteFinanciamiento")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("FuenteFinanciamientoId");

                    b.Navigation("EstructuraPresupuestaria");

                    b.Navigation("FuenteFinanciamiento");
                });

            modelBuilder.Entity("Domain.Entities.CuentaBancaria", b =>
                {
                    b.HasOne("Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany("Cuentas")
                        .HasForeignKey("BeneficiarioId");

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("Domain.Entities.DocumentosRespaldo", b =>
                {
                    b.HasOne("Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany("DocumentosRespaldo")
                        .HasForeignKey("BeneficiarioId");

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("Domain.Entities.Beneficiario", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("DocumentosRespaldo");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Domain.Entities.EstructuraPresupuestaria", b =>
                {
                    b.Navigation("Beneficiarios");
                });

            modelBuilder.Entity("Domain.Entities.FuenteFinanciamiento", b =>
                {
                    b.Navigation("Beneficiarios");
                });
#pragma warning restore 612, 618
        }
    }
}
